#pragma once

#define FORCE_NKRO
#define UNICODE_SELECTED_MODES UC_WINC, UC_MAC, UC_LNX
#define UNICODE_CYCLE_PERSIST false

#ifdef AUDIO_ENABLE
#define STARTUP_SONG SONG(PLANCK_SOUND)
#define DEFAULT_LAYER_SONGS { \
    SONG(QWERTY_SOUND),       \
    SONG(COLEMAK_SOUND),      \
    SONG(DVORAK_SOUND)        \
}
#define UNICODE_SONG_MAC  SONG(AUDIO_ON_SOUND)
#define UNICODE_SONG_LNX  SONG(UNICODE_LINUX)
#define UNICODE_SONG_BSD  SONG(TERMINAL_SOUND)
#define UNICODE_SONG_WIN  SONG(UNICODE_WINDOWS)
#define UNICODE_SONG_WINC SONG(UNICODE_WINDOWS)
#endif // AUDIO_ENABLE

#define TAPPING_TERM_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
